TSDB_HOST: 127.0.0.1
TSDB_USER: postgres
TSDB_PASS: abcdefg
TSDB_DATABASE: sgmp
DATABASE_URL: mysql://sgmp:abcdefg@127.0.0.1/sgmp
IOT_CERT_ID: abcdefg
IOT_ENDPOINT: abcdefg-ats.iot.us-west-1.amazonaws.com
IOT_CERT_PATH: iot_certs/device.crt
IOT_KEY_PATH: iot_certs/private.key
IOT_ROOT_PATH: iot_certs/AmazonRootCA1.pem
AWS_REGION: us-west-1
COGNITO_USER_POOL_ID: us-west-1_abcdefg
COGNITO_APP_CLIENT_ID: abcdefg
ENFORCE_AUTHENTICATION: 1
DEPLOYMENT_NAME: gismolab_sgmp